### ISSUE TITLE
Fix Hydration Issue on Next.js

### ISSUE THREAD

**Issue by YounesBessa** [tonightpass/kitchen#64]
How to reproduce ?

1. Go to http://localhost:3000/
2. Select light theme
3. Go to http://localhost:3000/checkbox
4. Reload the page
You're probably going to see an error message, and if not, you're going to see the background of the checkbox white instead of black

**Comment by AntoineKM** [comment]
Fixed on the docs thanks to next-themes but i will fix that overall

**Comment by AntoineKM** [comment]
I found a workaround in fact it would be necessary to pass the storage of the theme in cookie, like that when we load the page we could take the cookie in a getInitialProps and we would have the same theme of the server side and the client side
