### ISSUE TITLE
Documentation | Components - Add Button

### ISSUE THREAD

**Issue by AntoineKM** [tonightpass/kitchen#70]

**Comment by maddy020** [comment]
Hi @AntoineKM Can you describe  me where I have to insert the Button?

**Comment by AntoineKM** [comment]
Hey @maddy020,

Thanks for taking care of this issue!
Actually it's quite simple, we just ask you to take the code from `./examples/next-typescript/pages/button.tsx` and document it in `./docs/pages/docs/components/button.mdx`, as you can see there are already a few examples present in that one.

To start the project you just have to open 2 terminals:
```sh
// open terminal 1
yarn
yarn watch

// open terminal 2
cd ./docs
yarn
yarn dev

// open terminal 3 (optional this is only if you want to start the example)
cd ./examples/next-typescript
yarn
yarn dev
```
