### ISSUE TITLE
Documentation | Add Landing

### ISSUE THREAD

**Issue by AntoineKM** [tonightpass/kitchen#71]
Reference:
https://nextra.vercel.app
https://styled-components.com/showcase
https://chakra-ui.com/

**Comment by maddy020** [comment]
Please give me detailed over the issue

**Comment by AntoineKM** [comment]
Hello @maddy020,

Thanks for your interest in this issue but for the moment @ImAzyx is in charge of the design of the Landing, if you want you can see the references above to see what we want to inspire! If you're good at design, feel free to make suggestions below, otherwise if you just want to integrate this one, I'll notify you once @ImAzyx has finished the design of this one!
