### ISSUE TITLE
Add Logo

### ISSUE THREAD

**Issue by AntoineKM** [tonightpass/kitchen#72]

**Comment by maddy020** [comment]
Please give the details of the logo @AntoineKM

**Comment by AntoineKM** [comment]
Hello again @maddy020!

Thanks for your interest in this issue, we are looking to make a fairly simple and modern logo.
Actually @ImAzyx was supposed to do it but he might not have the time so you can do the logo if you want, if so we'd be super happy to have some examples below and then we could explain how to integrate it or do it ourselves depending on your convictions!

**Comment by maddy020** [comment]
Yeah I am ready to contribute 
Please give me details over the issue

**Comment by AntoineKM** [comment]
@maddy020 what more details do you need?

**Comment by AntoineKM** [comment]
https://cdn.discordapp.com/attachments/862052240867721216/1054369859519127582/kitchen.png
https://cdn.discordapp.com/attachments/862052240867721216/1054369615725211698/kitchen-icon.png
