### ISSUE TITLE
Documentation | Fix editor background color

### ISSUE THREAD

**Issue by AntoineKM** [tonightpass/kitchen#74]

**Comment by shivamhwp** [comment]
hi there @AntoineKM 
I am new to contributing, can you please tell me more about the issue like where I have to change the color?

**Comment by AntoineKM** [comment]
Hello @shivamhwp,

Welcome to contribute to Kitchen !

So to start I'll explain the outcome in more detail:

**How to reproduce ?**

**Comment by shivamhwp** [comment]
Ok

**Comment by AntoineKM** [comment]
Hello @shivamhwp,

Welcome to contribute to Kitchen !
So to start I'll explain the outcome in more detail:

**How to reproduce ?**
1. Go to https://kitchen.tonightpass.com/docs/components/badge
2. Click on "Code Editor"
3. On the bottom left of the screen, switch to `Light` theme

As you can probably see there is a color problem when we are in white, the light blue is too light etc.

To edit this one just go to: /docs/components/Playground/code-theme.ts

There are 2 solutions:
1. Edit this one
2. Make a "code-theme-dark" for the dark mode and a "code-theme-light" for the light mode

**Comment by AntoineKM** [comment]
Let's get started! To start the project you just have to open 2 terminals:
```
// open terminal 1
yarn
yarn watch

// open terminal 2
cd ./docs
yarn
yarn dev
```

**Comment by shivamhwp** [comment]
@AntoineKM 
changed some colors in code-theme.
